services:

  # postgres db container
  postgres_db:
    container_name: postgres_db
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #redis container
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  # core(fastapi project) container
  core:
    container_name: core
    build: .
    ports:
      - "8000:8000"

    depends_on:
      - postgres_db    
    volumes:
      - .:/core
    
    # --reload : restarting project for every change
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


volumes:
  postgres_data: